language: node_js
node_js:
- stable
before_install:
- npm i -g makeshift && makeshift -r registry.npmjs.org
install:
- npm install
before_script:
- npm install typescript -g
script:
- npm run lint
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
